@startuml
skinparam ParticipantFontSize 14
skinparam ParticipantFontColor #White
header "Entity First Pub/Sub"
title Entity First Pub-Sub Conceptual Sequence on Azure
participant ClientApp as "<b>Client App\n" #SlateGray
participant OrderService as "<b>Legacy Order\n<b>Service" #RoyalBlue
participant EntityStore as "<b>Data Store\n<i><<Relational DB>>" #DarkCyan
participant Publisher as "<b>Background Worker\n<i><<Azure Function>>" #DarkSlateBlue
participant EventHubs as "<b>Message Broker\n<i><<Event Hubs>>" #Darkorange

autonumber
activate ClientApp #Lime
ClientApp -> OrderService : Create Order
activate OrderService #Lime

OrderService -> EntityStore : 'INSERT INTO Orders'
activate EntityStore #Lime
EntityStore --> OrderService : Return OrderId

deactivate EntityStore
OrderService --> ClientApp : Return OrderId
deactivate OrderService
deactivate ClientApp


' #######################################################################
' hack so that the life bar on the entity store shows a seperation
'OrderService-[hidden]->OrderService
' #######################################################################

EntityStore <- Publisher : Read database log\n(<i>Change Data Capture</i>)
activate EntityStore #Lime
activate Publisher #Lime
Publisher -> Publisher : Derive orderCreated event\nbased on order table insert

Publisher -> EventHubs : Publish orderCreated event
activate EventHubs #Lime
EventHubs --> Publisher : Return success
deactivate EventHubs
Publisher -> EntityStore : CDC check-point
deactivate Publisher
deactivate EntityStore
@enduml