@startuml
skinparam ParticipantFontSize 14
skinparam ParticipantFontColor #White
header "Event First Pub/Sub"
title Event First Pub-Sub Conceptual Sequence on Azure
participant ClientApp as "<b>Client App\n" #SlateGray
participant OrderService as "<b>Order\n<b>Service" #RoyalBlue
participant EventStore as "<b>Event Store\n<i><<Cosmos DB>>" #DarkCyan
participant Publisher as "<b>Publisher\n<i><<Azure Function>>" #DarkSlateBlue
participant EventHubs as "<b>Message Broker\n<i><<Event Hubs>>" #Darkorange

autonumber
activate ClientApp #Lime
ClientApp -> OrderService : Submit <b>create_order</b> command

activate OrderService #Lime
OrderService -> EventStore : Append <b>order_created</b> event

activate EventStore #Lime
EventStore --> OrderService : Return success

deactivate EventStore
OrderService --> ClientApp : Return success

deactivate OrderService
deactivate ClientApp

EventStore <- Publisher : Read Change Feed\n(<i>Change Data Capture</i>)
activate EventStore #Lime

activate Publisher #Lime
Publisher -> EventHubs : Publish <b>order_created</b> event

activate EventHubs #Lime
EventHubs --> Publisher : Return success
deactivate EventHubs

Publisher -> EventStore : Update change feed\ncheck-point on lease container
deactivate Publisher
deactivate EventStore
@enduml